SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS SOMA_LIMITE FROM tabela_de_clientes
group by ESTADO;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS SOMA_LIMITE FROM tabela_de_clientes
group by ESTADO HAVING SUM(LIMITE_DE_CREDITO) > 900000; 

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO,
 MIN(PRECO_DE_LISTA) AS MENOR_PRECO FROM tabela_de_produtos
group by EMBALAGEM;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO,
 MIN(PRECO_DE_LISTA) AS MENOR_PRECO FROM tabela_de_produtos
group by EMBALAGEM HAVING SUM(PRECO_DE_LISTA <= 80);

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO,
 MIN(PRECO_DE_LISTA) AS MENOR_PRECO FROM tabela_de_produtos
group by EMBALAGEM HAVING SUM(PRECO_DE_LISTA) <= 80 AND MAX(PRECO_DE_LISTA) >= 5;